AllCops:
  Exclude:
    - db/schema.rb
    - db/migrate/*.rb
    - vendor/bundle/**/*

  DisplayCopNames: true

  DisplayStyleGuide: true

  TargetRubyVersion: 2.3

Rails:
  Enabled: true

Style/ExtraSpacing:
  AllowForAlignment: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Lambda:
  EnforcedStyle: literal

Performance/Casecmp:
  Enabled: false

inherit_from: .rubocop_todo.yml
